# GitHub Actions workflow that uses Arduino Lint to check for problems with Arduino projects
# Arduino Lint: https://github.com/arduino/arduino-lint
# Arduino Lint Action: https://github.com/arduino/arduino-lint-action

name: CI Arduino Lint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Checks-out Arduino Lint Action repository under, so your job can access it
      - uses: arduino/arduino-lint-action@v1
